version: "3.9"
services:
  api:
    build: .
    container_name: ticket-ai-api
    command: uvicorn server:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./webhooks.json:/app/webhooks.json
    environment:
      - PYTHONUNBUFFERED=1
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SHEET_ID=${SHEET_ID}
      - GOOGLE_SERVICE_ACCOUNT_EMAIL=${GOOGLE_SERVICE_ACCOUNT_EMAIL}
      - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
    restart: unless-stopped